
# path = "/home/pierre/research/tuthill/flywalk-pipeline-go/test2"
# model_folder = "/jellyfish/research/tuthill/DeepLabCut_pierre/pose-tensorflow/models"

path = "/media/beast/pierre/flywalk-pipeline-go/test2"
model_folder = "/home/tuthill/pierre/DeepLabCut_pierre/pose-tensorflow/models"

model_name = "flypose-subset-midpointsDec18-trainset95shuffle1"
model_train_iter = 1030000

compute_angles = true

nesting = 1

# 3d options
triangulate = true
calibration_prefix = "calib"
recording_prefix = "vid"

cam_regex = "_([A-Z])$"

[angles]
L1_CF = ["L1A", "L1B", "L1C"]
L1_FTi = ["L1B", "L1C", "L1D"]
L1_TiTa = ["L1C", "L1D", "L1E"]

L2_CF = ["L2A", "L2B", "L2C"]
L2_FTi = ["L2B", "L2C", "L2D"]
L2_TiTa = ["L2C", "L2D", "L2E"]

L3_CF = ["L3A", "L3B", "L3C"]
L3_FTi = ["L3B", "L3C", "L3D"]
L3_TiTa = ["L3C", "L3D", "L3E"]


[cameras.A]
offset = [224, 120, 832, 704] 

[cameras.B]
offset = [224, 230, 800, 700] 

[cameras.C]
offset = [160, 250, 864, 700] 


